"""Deterministic offline Mock LLM provider for zero-dependency local runs and testing.

Author: Jay Gautam (jaygautam561@gmail.com)
Project: 8byte Assessment
"""

import json
import re
from arxiv_digest.llm.base import BaseLLM


MOCK_TAG = "[MOCK]"


class MockLLM(BaseLLM):
    """Deterministic offline provider for tests and key-free runs.

    It never calls a model; its text is placeholder content, tagged with MOCK_TAG.
    """

    name = "mock"

    def generate(
        self,
        prompt: str,
        system_prompt: str | None = None,
        json_mode: bool = False,
    ) -> str:
        prompt_lower = prompt.lower()

        # Route on markers that only the intended prompt contains; paper text is part of
        # every prompt, so generic words like "select" would misroute.
        # 1. Paper ranking prompt (its JSON schema asks for "selected_index")
        if "selected_index" in prompt_lower:
            # Look for index numbers or return candidate index 0
            if json_mode:
                return json.dumps({
                    "selected_index": 0,
                    "rationale": "Directly addresses the primary research objective and methodology specified in the user topic."
                })
            return "0"

        # 2. Executive Briefing Generation
        # Content is visibly labelled as placeholder so mock output can never pass for a real
        # summary. Paper metadata (title, authors, ID) is filled in from arXiv by the summarizer.
        if "summary_plain_english" in prompt_lower:
            abstract_match = re.search(r"Abstract:\s*(.+?)(?:\n\n|$)", prompt, re.DOTALL)
            abstract = abstract_match.group(1).strip() if abstract_match else ""
            first_sentence = abstract.split(". ")[0].rstrip(".") + "." if abstract else "No abstract available."

            briefing_dict = {
                "summary_plain_english": f"{MOCK_TAG} First sentence of the abstract: {first_sentence}",
                "problem_statement": f"{MOCK_TAG} Problem statement would be generated by a live LLM.",
                "method_approach": [f"{MOCK_TAG} Method bullet placeholder."],
                "key_results_claims": [f"{MOCK_TAG} Results placeholder; no numbers are invented in mock mode."],
                "limitations": [f"{MOCK_TAG} Limitations placeholder."],
                "suggested_followup_questions": [
                    "What problem does this paper address?",
                    "What are the main results?",
                    "What limitations do the authors acknowledge?",
                ],
            }
            return json.dumps(briefing_dict)

        # 3. QA Grounded Response
        if "question" in prompt_lower or "answer based only on" in prompt_lower:
            # Check if there is context provided
            context_match = re.search(r"Context:?\s*(.*?)(?:Question:|$)", prompt, re.DOTALL | re.IGNORECASE)
            context_text = context_match.group(1).strip() if context_match else ""

            # Check if out of scope / hallucination test
            if "capital of france" in prompt_lower or "weather" in prompt_lower or "unrelated" in prompt_lower:
                return (
                    "I cannot answer this question based on the provided paper. "
                    "The paper does not mention or cover this topic, and my answers are strictly grounded in the document text."
                )

            if context_text and len(context_text) > 20:
                first_sentence = context_text.split(".")[0].strip()
                return f"{MOCK_TAG} Most relevant retrieved passage begins: {first_sentence}. [Source 1]"

            return "The paper does not contain sufficient information to answer this specific query."

        # Default fallback
        if json_mode:
            return json.dumps({"status": "ok", "message": "Processed successfully"})
        return "Mock response generated successfully."
